
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import styles from "./layout.module.css";

import { Roboto, Poppins } from 'next/font/google';

// on importe les polices de caractères car parfois il faut faire telecharger des polices de caractères à l utlisateur pour avoir le rendu souhaité
// ensuite on cree des const
/* mon degradé pour la page de reservation
 background: linear-gradient(45deg, 
#b7c8b7 20%, 
rgba(210, 230, 210, 0.8) 30%, 
rgba(255, 255, 255, 0.7) 50%, 
rgba(224, 224, 224, 0.9) 70%, 
#ffffff 90%);*/
const roboto = Roboto({

  weight: ['400', '700'], // 400 et 700 sont des tailles selon ce qui a été obersé sur google font
  style: ['normal', 'italic'], // donc en ce moment on a deja chargé 4 polices de caractères de base roboto
  subsets:['latin'],
    display:'swap',
    variable: '--font-roboto' // toutes les variables dans css commencent par deux tirets.
  
})

const poppins = Poppins({
  weight: '700',
  style: 'normal',
  subsets:['latin'],
    display:'swap',
    variable: '--font-poppins' // toutes les variables dans css commencent par deux tirets.
  

})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.variable + ' ' + poppins.variable}>
      <body  className={styles.body} >
        <Header> </Header>
        <main className={styles.main}>
         {children} 
        </main>

        <Footer/>

      </body>
      
    </html>
  );
}
